In [2]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [3]:
df = pd.read_csv('movies_metadata.csv')

In [4]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [5]:
df.shape

(45466, 24)

In [6]:
df.size

1091184

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [8]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [9]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [10]:
df = df.drop_duplicates().reset_index(drop=True)

In [11]:
df.duplicated().sum()

0

In [12]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [13]:
df = df[['title','genres','overview','tagline','popularity','vote_average']]

In [14]:
df

,title,genres,overview,tagline,popularity,vote_average
0,Toy Story,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...","Led by Woody, Andy's toys live happily in his ...",NaN,21.946943,7.7
1,Jumanji,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,17.015539,6.9
2,Grumpier Old Men,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,11.7129,6.5
3,Waiting to Exhale,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...","Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,3.859495,6.1
4,Father of the Bride Part II,"[{'id': 35, 'name': 'Comedy'}]",Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,8.387519,5.7
...,...,...,...,...,...,...
45448,Subdue,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",Rising and falling between a man and woman.,Rising and falling between a man and woman,0.072051,4.0
45449,Century of Birthing,"[{'id': 18, 'name': 'Drama'}]",An artist struggles to finish his work while a...,NaN,0.178241,9.0
45450,Betrayal,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...","When one of her hits goes wrong, a professiona...",A deadly game of wits.,0.903007,3.8
45451,Satan Triumphant,[],"In a small town live two brothers, one a minis...",NaN,0.003503,0.0
45452,Queerama,[],50 years after decriminalisation of homosexual...,NaN,0.163015,0.0

In [15]:
df.isnull().sum()

title               6
genres              0
overview          954
tagline         25045
popularity          5
vote_average        6
dtype: int64

In [16]:
df = df.dropna(subset=['title'])

In [17]:
df['overview'] = df['overview'].fillna('')

In [18]:
df.iloc[0]['genres']

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [19]:
import ast
df['genres'] = df['genres'].apply(lambda x : " ".join([i['name'] for i in ast.literal_eval(x)]))

In [20]:
df.head()

,title,genres,overview,tagline,popularity,vote_average
0,Toy Story,Animation Comedy Family,"Led by Woody, Andy's toys live happily in his ...",NaN,21.946943,7.7
1,Jumanji,Adventure Fantasy Family,When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,17.015539,6.9
2,Grumpier Old Men,Romance Comedy,A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,11.7129,6.5
3,Waiting to Exhale,Comedy Drama Romance,"Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,3.859495,6.1
4,Father of the Bride Part II,Comedy,Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,8.387519,5.7

In [21]:
df['tagline'] = df['tagline'].fillna('')

In [22]:
df.isnull().sum()

title           0
genres          0
overview        0
tagline         0
popularity      0
vote_average    0
dtype: int64

In [23]:
df['tags'] = df['genres'] + " " + df['overview'] + " " + df['tagline']

In [24]:
df

,title,genres,overview,tagline,popularity,vote_average,tags
0,Toy Story,Animation Comedy Family,"Led by Woody, Andy's toys live happily in his ...",,21.946943,7.7,"Animation Comedy Family Led by Woody, Andy's t..."
1,Jumanji,Adventure Fantasy Family,When siblings Judy and Peter discover an encha...,Roll the dice and unleash the excitement!,17.015539,6.9,Adventure Fantasy Family When siblings Judy an...
2,Grumpier Old Men,Romance Comedy,A family wedding reignites the ancient feud be...,Still Yelling. Still Fighting. Still Ready for...,11.7129,6.5,Romance Comedy A family wedding reignites the ...
3,Waiting to Exhale,Comedy Drama Romance,"Cheated on, mistreated and stepped on, the wom...",Friends are the people who let you be yourself...,3.859495,6.1,"Comedy Drama Romance Cheated on, mistreated an..."
4,Father of the Bride Part II,Comedy,Just when George Banks has recovered from his ...,Just When His World Is Back To Normal... He's ...,8.387519,5.7,Comedy Just when George Banks has recovered fr...
...,...,...,...,...,...,...,...
45448,Subdue,Drama Family,Rising and falling between a man and woman.,Rising and falling between a man and woman,0.072051,4.0,Drama Family Rising and falling between a man ...
45449,Century of Birthing,Drama,An artist struggles to finish his work while a...,,0.178241,9.0,Drama An artist struggles to finish his work w...
45450,Betrayal,Action Drama Thriller,"When one of her hits goes wrong, a professiona...",A deadly game of wits.,0.903007,3.8,Action Drama Thriller When one of her hits goe...
45451,Satan Triumphant,,"In a small town live two brothers, one a minis...",,0.003503,0.0,"In a small town live two brothers, one a mini..."
45452,Queerama,,50 years after decriminalisation of homosexual...,,0.163015,0.0,50 years after decriminalisation of homosexua...

In [25]:
df['tags'][0]

"Animation Comedy Family Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences. "

In [27]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [28]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Puneet\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Puneet\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [29]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

The history saving thread hit an unexpected error (OperationalError('database or disk is full')).History will not be written to the database.

In [30]:
def preprocess_text(text):
    #lowercase
    text = str(text).lower()
    #removed the punctuations
    text = re.sub(r'[^a-zA-Z\s]','', text)

    words = text.split()  #split the text into individual words
    #remove stopwords
    words = [word for word in words if word not in stop_words]

    #lemmatize
    words = [lemmatizer.lemmatize(word) for word in words]

    return " ".join(words)  #convert list of words back to string

In [31]:
df['tags'] = df['tags'].apply(preprocess_text)

In [32]:
df['tags'][0]

'animation comedy family led woody andys toy live happily room andys birthday brings buzz lightyear onto scene afraid losing place andys heart woody plot buzz circumstance separate buzz woody owner duo eventually learns put aside difference'

In [33]:
df = df.reset_index(drop=True)

In [34]:
indices = pd.Series(df.index, index=df['title']).drop_duplicates()
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Subdue                         45442
Century of Birthing            45443
Betrayal                       45444
Satan Triumphant               45445
Queerama                       45446
Length: 45447, dtype: int64

In [43]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [44]:
tfidf = TfidfVectorizer(max_features=10000,ngram_range=(1, 1), stop_words='english')

In [45]:
tfidf_matrix = tfidf.fit_transform(df['tags'])

In [46]:
tfidf_matrix

<45447x10000 sparse matrix of type '<class 'numpy.float64'>'
	with 1156335 stored elements in Compressed Sparse Row format>

In [47]:
from sklearn.metrics.pairwise import cosine_similarity

In [48]:
def recommend(title, n=10):
    if title not in indices:
        return "Movie not found in the dataset."
    
    idx = indices[title]
    sim_score = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()
    similar_idx = sim_score.argsort()[::-1][1:n+1]
    return df['title'].iloc[similar_idx]

In [49]:
recommend('Toy Story')

15344               Toy Story 3
2996                Toy Story 2
24512                 Small Fry
6434     What's Up, Tiger Lily?
17184                 Group Sex
11396    For Your Consideration
25560           Listen, Darling
1071      Rebel Without a Cause
39593                     Ozzie
1931                  Condorman
Name: title, dtype: object

In [50]:
import pickle

pickle.dump(df, open('df.pkl', 'wb'))
pickle.dump(tfidf_matrix, open('tfidf_matrix.pkl', 'wb'))
pickle.dump(indices, open('indices.pkl', 'wb'))
pickle.dump(tfidf, open('tfidf.pkl', 'wb'))